[project]
name = "acm-tasks"
version = "0.1.0"
requires-python = ">=3.13.3"
dependencies = [
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "numpy>=2.2.5",
    "plotly>=6.1.0",
    "yfinance>=0.2.61",
]
